apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'sinatra'
        metrics_path: /metrics
        static_configs:
          - targets: ['sinatra-service.default.svc.cluster.local:8000']
